Syslog yes
SyslogSuccess yes
LogWhy yes
Canonicalization relaxed/simple
Mode sv
SubDomains no
OversignHeaders From
Socket inet:8891@127.0.0.1
Domain example.com
Selector mcms
KeyFile /etc/opendkim/keys/example.com/mcms.private
