ALTER TABLE purchase_order ADD COLUMN IF NOT EXISTS paid BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE purchase_order ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP;
ALTER TABLE purchase_order ADD COLUMN IF NOT EXISTS in_transit BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE purchase_order ADD COLUMN IF NOT EXISTS expected_arrival_date DATE;
ALTER TABLE purchase_order ADD COLUMN IF NOT EXISTS receiving_notes VARCHAR(1000);
ALTER TABLE purchase_order ADD COLUMN IF NOT EXISTS missing_items VARCHAR(1000);
